feat(combined-report-ui): Report order and scan details icons
microsoft/accessibility-insights-web pull request #3493
Opened 2020-10-19 23:05 UTC by JGibson2019

#### Description of changes
- Switched the order in report body so details section comes before the summary
- Added the icons for the scan details section

#### Pull request checklist

- [ ] Addresses an existing issue: #0000
- [ ] Ran `yarn fastpass`
- [ ] Added/updated relevant unit test(s) (and ran `yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

2020-10-20 21:15 UTC, dbjorge requested changes
The order switching looks fine in the fastpass report generated by web, but it looks like there's still a few CSS/formatting inconsistencies between the figma and this update:

* All of the "content" text in Scan Details should be offset 40px from the left edge of the card to account for space for the icons (the icons should be 20px offset from the left edge)
* Should be 16px margin between the "Scan details" `<h2>` and the card content (is currently 14px)
* Should be 6px extra space between the "target site" line and the "scans started" line
* Should be 22px space between "scan details" and "url" cards

Screenshot from figma:
![screenshot of figma spec](https://user-images.githubusercontent.com/376284/96644268-cb7aa780-12f6-11eb-953b-acdbf18c50c7.png)

Screenshot of `node .\dist\ai-scan-cli.js --url https://accessibilityinsights.io --crawl` result after integrating a build from commit 8d24fd1:
![screenshot of summary report with this change](https://user-images.githubusercontent.com/376284/96644067-82c2ee80-12f6-11eb-81a6-a6318fd87d01.png)

2020-10-23 01:17 UTC, JGibson2019 commented
> The order switching looks fine in the fastpass report generated by web, but it looks like there's still a few CSS/formatting inconsistencies between the figma and this update:
> 
> * All of the "content" text in Scan Details should be offset 40px from the left edge of the card to account for space for the icons (the icons should be 20px offset from the left edge)
> * Should be 16px margin between the "Scan details" `<h2>` and the card content (is currently 14px)
> * Should be 6px extra space between the "target site" line and the "scans started" line
> * Should be 22px space between "scan details" and "url" cards
> 
> Screenshot from figma:
> ![screenshot of figma spec](https://user-images.githubusercontent.com/376284/96644268-cb7aa780-12f6-11eb-953b-acdbf18c50c7.png)
> 
> Screenshot of `node .\dist\ai-scan-cli.js --url https://accessibilityinsights.io --crawl` result after integrating a build from commit [8d24fd1](https://github.com/microsoft/accessibility-insights-web/commit/8d24fd1a5ea8daa1ef8b77b7841300ed841a9eee):
> ![screenshot of summary report with this change](https://user-images.githubusercontent.com/376284/96644067-82c2ee80-12f6-11eb-81a6-a6318fd87d01.png)

Regarding the left offset, I kept it consistent with the summary view for the automated checks summary report (not sure how much we want to deviate, but can go back and change that if this is a problem). 

I changed the Scan details h2 margin and the space between the cards

For the different spacing for the lines with icons vs. without icons, I had to do a bit of tinkering to get the starting letters to line up perfectly (ended up with a 29px padding, but that seems to render consistent results regardless of zoom level) 

Last, for the 6px extra space between "Target site" and "Scans started", @ferBonnin is this a need to have or is what's in the screenshot below ok? I ask for two reasons

1. We don't do this for the Automated Checks report, so not sure how consistent we want to be

1. It's proven not as straightforward to add the extra spacing for that specific styling; one option is to have two unordered list elements, one for the target site item and one for the scan information, and then overriding inherited margins for that element. When I tried this out earlier, it resulted in too much space between elements. That said, if this is something we need for the design I can try to figure it out! 


![image](https://user-images.githubusercontent.com/19158512/96945271-2268b400-1492-11eb-8748-fb36bfe332d8.png)

2020-10-23 01:35 UTC, ferBonnin commented
>  @ferBonnin is this a need to have or is what's in the screenshot below ok?

ok as it is in the screenshot

2020-10-23 18:51 UTC, dbjorge approved these changes

2020-10-23 19:04 UTC, merged