chore: Enzyme replacement in test files (Part 3)
microsoft/accessibility-insights-web pull request #7232
Opened 2024-02-02 13:17 UTC by v-singhanjal

#### Details

##### Motivation

##### Context

#### Pull request checklist

- [ ] Addresses an existing issue: #0000
- [ ] Ran `yarn fastpass`
- [ ] Added/updated relevant unit test(s) (and ran `yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

2024-02-05 11:20 UTC, v-rakeshsh commented on src/tests/unit/tests/DetailsView/components/switcher.test.tsx
> +            expect(dropdown).toMatchSnapshot();
hope this dropdown has options props?

2024-02-05 11:30 UTC, v-singhanjal commented on src/tests/unit/tests/DetailsView/components/tab-stops-requirement-instances-collapsible-content.test.tsx
> +        await userEvent.click(button[1]);
There was a forEach loop here. The loop was not working for the 2 buttons so added separately for each button.

2024-02-05 13:11 UTC, v-singhanjal commented on src/tests/unit/tests/DetailsView/components/switcher.test.tsx
> +            expect(dropdown).toMatchSnapshot();
Made the change

2024-03-01 17:04 UTC, madalynrose requested changes
This looks awesome! There were a lot of complex tests here. I made some suggestions and once those are implemented it's ready to go!

2024-03-01 17:04 UTC, madalynrose commented on src/tests/unit/tests/DetailsView/details-view-container.test.tsx
> +            ]);
This isn't actually needed
```suggestion
```

2024-03-01 17:04 UTC, madalynrose commented on src/tests/unit/tests/DetailsView/details-view-container.test.tsx
> +            ]);
```suggestion
```

2024-03-01 17:04 UTC, madalynrose commented on src/tests/unit/tests/DetailsView/details-view-container.test.tsx
> +    useOriginalReactElements,
We end up not needing this.
```suggestion
```

2024-03-04 16:59 UTC, madalynrose approved these changes

2024-03-05 05:26 UTC, merged