chore: Typescript Cleanup- Part 5 for Errors - urls,cardsViewStoreData,storeActionMessageCreator,browserSpec
microsoft/accessibility-insights-web pull request #7302
Opened 2024-04-10 13:10 UTC by JeevaniChinthala

#### Details

As part of Typescript migration added/removed the error causing fields.

##### Motivation

TypeScript 5.0 has marked some options as deprecated. We can temporarily override these deprecations, but the documented plan is for the ability to override the flag to go away in TypeScript 5.5

##### Context

#### Pull request checklist

- [x] Addresses an existing issue: #(https://github.com/microsoft/accessibility-insights-web/pull/6611)
- [ ] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

2024-04-18 12:59 UTC, JeevaniChinthala commented on src/DetailsView/details-view-initializer.ts
> -                scopingFlagsHandler,
When 'axeResultToIssueFilingDataConverter' property from the same file is resolved, then we are getting issue for this property checked using tbuild:all. Hence resolved.

2024-04-18 12:59 UTC, JeevaniChinthala commented on src/DetailsView/details-view-initializer.ts
> -                Assessments,
When 'axeResultToIssueFilingDataConverter' property from the same file is resolved, then we are getting issue for this property checked using tbuild:all. Hence resolved.

2024-04-18 12:59 UTC, JeevaniChinthala commented on src/DetailsView/details-view-initializer.ts
> -            const scopingFlagsHandler = new PreviewFeatureFlagsHandler(getAllFeatureFlagDetails());
When 'axeResultToIssueFilingDataConverter' property from the same file is resolved, then we are getting issue for this property checked using tbuild:all. Hence resolved.

2024-04-19 15:03 UTC, JeevaniChinthala commented on src/DetailsView/components/tab-stops/tab-stops-instance-section-props-factory.tsx
> -                        requirementId={result.id}
Yes. Tested

2024-05-01 20:54 UTC, madalynrose requested changes

2024-05-02 05:34 UTC, JeevaniChinthala commented on src/DetailsView/components/save-assessment-button.tsx
> -                                    value={
Updated

2024-05-02 05:34 UTC, JeevaniChinthala commented on src/common/components/visualization-toggle.tsx
>          };
Updated.

2024-05-02 05:34 UTC, JeevaniChinthala commented on src/reports/components/report-sections/report-collapsible-container.tsx
> +    onExpandToggle: (event: React.MouseEvent<HTMLDivElement>) => void;
Updated.

2024-05-02 14:11 UTC, madalynrose approved these changes

2024-05-03 04:51 UTC, merged